sequenceDiagram
    participant User
    participant Library
    participant Book

    User->>Library: requestCreateLoan()
    Library->>Book: markAsUnavailable()
    create participant Loan
    Library->>Loan: create()
    Library-->>User: loan created
